version: '3'

services:
  database:
    image: 'postgres:latest'
    container_name: langlang-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
 
volumes:
  postgres_data: